name: Deploy

on:
  pull_request:
    branches: [main]

jobs:
  deployment:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Copy env # copy in your env file
        run: 'echo -e "${{secrets.FRONTEND_ENV}}" > .env'
        working-directory: ./apps/client

      - name: Install dependencies
        working-directory: ./apps/client
        run: |
          npm install -g pnpm
          pnpm install
      - name: Deploy
        working-directory: ./apps/client
        run: |
          npx sst deploy --stage ${{env.pr_id}}
