packages:
  # all packages in subdirs of packages/ and components/
  - 'packages/**'
  # exclude packages that are inside test directories
  - '!**/test/**'
  - '!**/__tests__/**'


catalog:
  typescript: ^5.5.3
  zod: ^3.23.8
  "framer-motion": "^11.3.27"

catalogs:
  react18:
    react: 18.3.1
    react-dom: 18.3.1
    "@types/react": ^18.3.3
    "@types/react-dom": ^18.3.0