/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "AuthGithubId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "AuthGithubSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "AuthGoogleId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "AuthGoogleSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "AuthResendKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "AuthSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "AuthTrustHost": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "CacheTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "DatabaseUrl": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "EventBus": {
      "arn": string
      "name": string
      "type": "sst.aws.Bus"
    }
    "GaslessKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ImageUploads": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "LoopsApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "NextPublicWalletConnectProjectId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "NormieTechApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "NormieTechSecretKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "OpenAiApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Router": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "RpcUrl": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ScheduleReceivingLambda": {
      "arn": string
      "type": "sst.aws.Function"
    }
    "SecretKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "schedulerRole": {
      "arn": string
      "type": "aws.iam/role.Role"
    }
    "website": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
  }
}
