name: Build on Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Copy env # copy in your env file
        run: 'echo -e "${{secrets.BACKEND_ENV}}" > .env'
        working-directory: ./apps/backend

      - name: Install dependencies
        run: yarn install --prefer-offline --frozen-lockfile
        working-directory: ./apps/backend

      - name: Build
        run: npm run build
        working-directory: ./apps/backend
