name: Deploy

on:
  push:
    branches:
      - dev

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        working-directory: ./apps/client
        run: |
          npm install -g pnpm
          pnpm install
      - name: Deploy
        working-directory: ./apps/client
        run: |
          npx sst deploy --stage prod
